### ISSUE TITLE
Interested on PR's for missing days?

### ISSUE THREAD

**Issue by Average-user** [sindrekjr/AdventOfCode2017#1]

**Comment by sindrekjr** [comment]
Sure, anything in particular you had in mind? I've taken a break from the tasks, but I'm planning on solving them on my own eventually, preferably in some of the languages that I haven't used a lot (or Clojure). Some solutions/suggestions to approaches for the remaining tasks is welcome, anyway.

**Comment by Average-user** [comment]
It was more because I didn't want this to be incomplete, but if you are going to implement them that is all right
